version: "3"
services:
  sftp:
    image: atmoz/sftp:alpine
    container_name: sftp
    volumes:
      - ./local/sftp/out:/home/user1/out
      - ./local/sftp/users.conf:/etc/sftp/users.conf:ro
    ports:
      - "2222:22"

